services:
  chegahoje_bot:
    build: .
    container_name: chegahoje_bot
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      TZ: "America/Sao_Paulo"
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    volumes:
      - database:/database

volumes:
    database: